name: PSSpred Software

on:
  push:
    branches:
      - master

#jobs:
#  build_docs_and_deploy:
#    runs-on: ubuntu-latest
#    name: building PSSpred
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@master
#
#    - name: running psspred
#      run: |
#         git config --global user.email "ucecwme@ucl.ac.uk"
#         git config --global user.name "nickcafferry"
#         git init
#         echo "Initializing the program....................."
#         
#         echo "---------------------------------------------"
#         cd ../
#         mkdir software
#         cd software/
#         mkdir nr
#         mkdir PSSpred_v4/
#         cd ../
#         echo "software file already created!"
#         
#         echo "---------------------------------------------"
#         cd PSSpred/
#         cd src/
#         mkdir nr
#         cd nr/
#         wget -O nr.tar.gz https://zhanglab.ccmb.med.umich.edu/cgi-bin/download_ftp.cgi?ID=nr.tar.gz
#         tar -zxvf nr.tar.gz
#         rm nr.tar.gz
#         echo "nr.tar.gz already unpacked!"
#         echo "Show the path of this file: "
#         pwd
#         echo "---------------------------------------------"
#         
#         cd ../
#         cp -r nr/. /home/runner/work/PSSpred/software/nr/
#         cp -r PSSpred_v4/. /home/runner/work/PSSpred/software/PSSpred_v4/
#         
#         echo "checking the artifacts..."
#         cd /home/runner/work/PSSpred/software/
#         ls
#         pwd
#         
#    - uses: actions/upload-artifact@v2
#      with:
#        name: software(linux)
#        path: /home/runner/work/PSSpred/software/ 
         
