#         git lfs install
#         echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
#         git lfs pull
name: PSSpred docs

on:
  push:
    branches:
      - master

#jobs:
#  build_docs_and_deploy:
#    runs-on: ubuntu-latest
#    name: Protein Secondary Structure prediction
#
#    steps:
#    - name: Checkout
#      uses: actions/checkout@master
#
#    - name: Clone pre repositories
#      run: |
#         git config --global user.email "ucecwme@ucl.ac.uk"
#         git config --global user.name "nickcafferry"
#         git init
#         ls
#         
#         cd src/
#         git rm -rf nr_data
#         git commit -m "delete some irrelevant materials"
#         git push origin master
#
#
#         mkdir PSSpred_v1
#         cd PSSpred_v1/
#         wget https://zhanglab.ccmb.med.umich.edu/PSSpred/PSSpred_v1.tar.gz
#         tar -zxvf PSSpred_v1.tar.gz
#         rm PSSpred_v1.tar.gz
#         ls
#         git add -A
#         git commit -m "add PSSred_v1"
#         pwd
#         cd ../../
#         git push origin master
